# -*- coding: utf-8 -*-
"""Lab1_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13OXYaPlniNqBmP1IF92d-umSe5oWmKF8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')
#4/1AX4XfWh-ZvI6MDn6nE40xEylYknZvmcMCdxSyNy-o6I0uivbCdFFaTb_NvQ

data=pd.read_csv('/content/drive/My Drive/ML_DATA/mtcars.csv')
d = pd.crosstab(index=data['cyl'],columns="count",dropna=True)
print(d)

print(data.info())

#count total Null values in each column
print("Total Null Data:",data.isnull().sum())

#Finding the histogram
#From the given dataset 'mtcars.csv',plot a histogram to check frequency distribution on of the varibale 'mpg' (miles per gallon)
plt.hist(data['mpg'],bins=5)
plt.show()

#scatter plot of 'mpg' (Miles per gallon) vs 'wt' (weight of car)
plt.scatter(data['mpg'],data['wt'])
plt.show()

#In the dataframe, under the variable gear count count total records in each value.
df = pd.DataFrame(data,columns=['gear'])
print("Count How many values:\n",df['gear'].value_counts())

#Exercise Question
#1. Draw a scatter plot between age and salary for "Data_for_Transformation.csv" file
data2 = pd.read_csv('/content/drive/My Drive/ML_DATA/Data_for_Transformation.csv')
plt.scatter(data2['Age'],data2['Salary'])
plt.show()

#2. Draw a histogram of salary
plt.hist(data2['Salary'],bins=5)
plt.show()

plt.bar(data2['Country'],align='center',height=10.0)
plt.show()